name: Deploy Docker Image on Self-Hosted

on:
  repository_dispatch:
    types:
      - deploy-docker-image
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, Linux, Production, ARM64]
    steps:
    - name: Docker Stack Deploy 
      run: docker stack deploy --prune --resolve-image always -c /deploy/articleviewer/docker-compose.yml articleviewer
      shell: pwsh
